<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>annotations</Nullable>
    <AssemblyName>AccuSync.WPF</AssemblyName>
    <RootNamespace>AccuSync.WPF</RootNamespace>
    <Version>1.0.0</Version>
    <Company>Natus</Company>
    <Product>AccuSync</Product>
    <Description>Device Management System for Patient and Device Configurations</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>RELEASE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccuSync.Presentation\AccuSync.Presentation.csproj" />
    <ProjectReference Include="..\AccuSync.Core\AccuSync.Core.csproj" />
    <ProjectReference Include="..\AccuSync.Application\AccuSync.Application.csproj" />
    <ProjectReference Include="..\AccuSync.EF\AccuSync.EF.csproj" />
    <ProjectReference Include="..\AccuSync.Adapters.DataParser\AccuSync.Adapters.DataParser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Images\company_logo.png" />
    <None Remove="Resources\Images\splash.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\company_logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\splash.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
