// <auto-generated />
using AccuSync.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccuSync.EF.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260811114902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AccuSync.Core.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AccuScreenAllTests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccuScreenBasicTests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccuScreenDeletePatients")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccuScreenEditPatients")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccuScreenQuickTest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<bool>("DeviceAddEdit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeviceConfigureTestModules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeviceDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeviceView")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PatientsAddEdit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsCommentMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsConfigurePatientManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsReassignTests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsRiskFactorMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientsView")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesAddEditFacilities")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesAddEditSites")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesConfigureSiteFacilityManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesDeleteFacilities")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesDeleteSites")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesViewFacilities")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SitesViewSites")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SysConfigConfigureApplication")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SysConfigViewConfiguration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesAddEditProfiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesAddEditUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesConfigureUserProfileManagement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesDeleteProfiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesDeleteUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesResetUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesViewProfiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsersProfilesViewUsers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            AccuScreenAllTests = true,
                            AccuScreenBasicTests = true,
                            AccuScreenDeletePatients = true,
                            AccuScreenEditPatients = true,
                            AccuScreenQuickTest = true,
                            Description = "Full access, including user and system administration.",
                            DeviceAddEdit = true,
                            DeviceConfigureTestModules = true,
                            DeviceDelete = true,
                            DeviceView = true,
                            IsSystemDefined = true,
                            Name = "Admin",
                            PatientsAddEdit = true,
                            PatientsCommentMaintenance = true,
                            PatientsConfigurePatientManagement = true,
                            PatientsDelete = true,
                            PatientsReassignTests = true,
                            PatientsRiskFactorMaintenance = true,
                            PatientsView = true,
                            SitesAddEditFacilities = true,
                            SitesAddEditSites = true,
                            SitesConfigureSiteFacilityManagement = true,
                            SitesDeleteFacilities = true,
                            SitesDeleteSites = true,
                            SitesViewFacilities = true,
                            SitesViewSites = true,
                            SysConfigConfigureApplication = true,
                            SysConfigViewConfiguration = true,
                            UsersProfilesAddEditProfiles = true,
                            UsersProfilesAddEditUsers = true,
                            UsersProfilesConfigureUserProfileManagement = true,
                            UsersProfilesDeleteProfiles = true,
                            UsersProfilesDeleteUsers = true,
                            UsersProfilesResetUsers = true,
                            UsersProfilesViewProfiles = true,
                            UsersProfilesViewUsers = true
                        },
                        new
                        {
                            Id = "Screener",
                            AccuScreenAllTests = true,
                            AccuScreenBasicTests = true,
                            AccuScreenDeletePatients = false,
                            AccuScreenEditPatients = true,
                            AccuScreenQuickTest = true,
                            Description = "Least-privileged profile; sees only day-to-day screening features.",
                            DeviceAddEdit = false,
                            DeviceConfigureTestModules = false,
                            DeviceDelete = false,
                            DeviceView = true,
                            IsSystemDefined = true,
                            Name = "Screener",
                            PatientsAddEdit = true,
                            PatientsCommentMaintenance = true,
                            PatientsConfigurePatientManagement = false,
                            PatientsDelete = false,
                            PatientsReassignTests = false,
                            PatientsRiskFactorMaintenance = false,
                            PatientsView = true,
                            SitesAddEditFacilities = false,
                            SitesAddEditSites = false,
                            SitesConfigureSiteFacilityManagement = false,
                            SitesDeleteFacilities = false,
                            SitesDeleteSites = false,
                            SitesViewFacilities = true,
                            SitesViewSites = true,
                            SysConfigConfigureApplication = false,
                            SysConfigViewConfiguration = true,
                            UsersProfilesAddEditProfiles = false,
                            UsersProfilesAddEditUsers = false,
                            UsersProfilesConfigureUserProfileManagement = false,
                            UsersProfilesDeleteProfiles = false,
                            UsersProfilesDeleteUsers = false,
                            UsersProfilesResetUsers = false,
                            UsersProfilesViewProfiles = true,
                            UsersProfilesViewUsers = true
                        });
                });

            modelBuilder.Entity("AccuSync.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("FailedLoginAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("FailedResetAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("FirstFailedLoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("FirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstResetLoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastThreePasswords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<long>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("PasswordModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("UsernameHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UsernameHash")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.User", b =>
                {
                    b.HasOne("AccuSync.Core.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
