// <auto-generated />
using System;
using AccuSync.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccuSync.EF.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsentState")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Deceased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Discharged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeField1Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeField2Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeField3Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeField4Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeText3")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GestationalAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HospitalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Medication")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NicuStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientRecordNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredefinedComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreeningConsent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingConsent")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsExported");

                    b.HasIndex("SiteId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.PatientContact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CalculatedDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("CellPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("IdNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalityCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.HasIndex("ContactType");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientContacts", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.PatientRiskFactorValue", b =>
                {
                    b.Property<int>("PatientRiskFactorValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskFactorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientRiskFactorValueId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RiskFactorId");

                    b.HasIndex("PatientId", "RiskFactorId")
                        .IsUnique();

                    b.ToTable("PatientRiskFactorValues", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.TestRecord", b =>
                {
                    b.Property<int>("TestRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Application")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentSerial")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchedDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchedProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedProtocolType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PredefinedComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreeningMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceBinauralRefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFacilityRefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceInstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocationRefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUserRefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestObject")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestTypeSignature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransducerCalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransducerNextCalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransducerSerial")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransducerTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("TestRecordId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("TestDate");

                    b.HasIndex("TestType");

                    b.ToTable("TestRecords", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.TestSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SessionDate");

                    b.ToTable("TestSessions", (string)null);
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.PatientContact", b =>
                {
                    b.HasOne("AccuSync.Core.Entities.Patients.Patient", null)
                        .WithMany("Contacts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.PatientRiskFactorValue", b =>
                {
                    b.HasOne("AccuSync.Core.Entities.Patients.Patient", null)
                        .WithMany("RiskFactorValues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.TestRecord", b =>
                {
                    b.HasOne("AccuSync.Core.Entities.Patients.TestSession", null)
                        .WithMany("TestRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.TestSession", b =>
                {
                    b.HasOne("AccuSync.Core.Entities.Patients.Patient", null)
                        .WithMany("TestSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.Patient", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("RiskFactorValues");

                    b.Navigation("TestSessions");
                });

            modelBuilder.Entity("AccuSync.Core.Entities.Patients.TestSession", b =>
                {
                    b.Navigation("TestRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
